name: auto-build
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: build
        run: |
          npm install
          npm run build
          rm -rf ./node_modules
          zip -r ./lite_tools_v4.zip ./*
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lite_tools_v4
          path: lite_tools_v4.zip
          retention-days: 3  # 文件保留3天
